POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Flower blossoms",
    "author": "Misha",
    "url": "https://www.flower.com/",
    "likes": 15,
    "userId": "648f4bffe43db1c25bdb1f84"
}